// <auto-generated />
using System;
using Easy2Move.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Easy2Move.Application.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260717174306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Easy2Move.Contracts.Models.BookingDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GeschatteDuurUren")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Huisnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KlantNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opmerkingen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tijdslot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Verdieping")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
